
using UnityEngine;

public class WeatherStates : MonoBehaviour
{
    public GameObject clearDay, clearNight, rainDay, rainNight, cloudsDay, cloudsNight, clouds, snowDay, snowNight, cloudsDayLight, cloudsNightLight, rainDayLight, rainNightLight, mistDay, mistNight, cloudsNightBroken, cloudsDayBroken;
    public void ClearDay()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(true);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void ClearNight()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(true);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void RainNight()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(true);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void RainDay()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(true);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void CloudsDay()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(true);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void CloudsNight()
    {
        cloudsNight.SetActive(true);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void SnowNight()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(true);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void SnowDay()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(true);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void RainDayLight()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(true);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void RainNightLight()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(true);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void CloudsDayLight()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(true);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void CloudsNightLight()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(true);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void MistDay()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(true);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void MistNight()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(true);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(false);
    }
    public void CloudsDayBroken()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(true);
        cloudsNightBroken.SetActive(false);
    }
    public void CloudsNightBroken()
    {
        cloudsNight.SetActive(false);
        clearDay.SetActive(false);
        clearNight.SetActive(false);
        rainDay.SetActive(false);
        rainNight.SetActive(false);
        cloudsDay.SetActive(false);
        snowNight.SetActive(false);
        snowDay.SetActive(false);
        rainDayLight.SetActive(false);
        rainNightLight.SetActive(false);
        cloudsDayLight.SetActive(false);
        cloudsNightLight.SetActive(false);
        mistDay.SetActive(false);
        mistNight.SetActive(false);
        cloudsDayBroken.SetActive(false);
        cloudsNightBroken.SetActive(true);
    }

    public void CloudCover()
    {
       // clouds.SetActive(true);
    }
}
